"""initial schema

Revision ID: 41d16dc059db
Revises: 
Create Date: 2026-02-20 13:24:27.100608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41d16dc059db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_gpa_records_user_date'), table_name='gpa_records')
    op.drop_table('gpa_records')
    op.drop_index(op.f('idx_moods_sentiment'), table_name='moods')
    op.drop_index(op.f('idx_moods_user_date'), table_name='moods')
    op.drop_table('moods')
    op.drop_index(op.f('idx_recommendations_priority'), table_name='recommendations')
    op.drop_index(op.f('idx_recommendations_user_active'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('idx_curation_query_created'), table_name='content_curation_queries')
    op.drop_index(op.f('idx_curation_query_topic'), table_name='content_curation_queries')
    op.create_index(op.f('ix_content_curation_queries_created_at'), 'content_curation_queries', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_curation_queries_topic'), 'content_curation_queries', ['topic'], unique=False)
    op.alter_column('courses', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('courses_code_key'), 'courses', type_='unique')
    op.drop_index(op.f('idx_courses_code'), table_name='courses')
    op.drop_index(op.f('idx_courses_department'), table_name='courses')
    op.drop_index(op.f('idx_courses_level'), table_name='courses')
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.drop_index(op.f('idx_curated_cache_expires'), table_name='curated_resources')
    op.drop_index(op.f('idx_curated_learning_style'), table_name='curated_resources')
    op.drop_index(op.f('idx_curated_resource_type_quality'), table_name='curated_resources')
    op.drop_index(op.f('idx_curated_topic'), table_name='curated_resources')
    op.drop_index(op.f('idx_curated_topic_learning_style'), table_name='curated_resources')
    op.drop_index(op.f('idx_curated_topic_quality'), table_name='curated_resources')
    op.create_index('idx_resource_type_quality', 'curated_resources', ['resource_type', 'quality_score'], unique=False)
    op.create_index('idx_topic_learning_style', 'curated_resources', ['topic', 'learning_style'], unique=False)
    op.create_index('idx_topic_quality', 'curated_resources', ['topic', 'quality_score'], unique=False)
    op.create_index(op.f('ix_curated_resources_cache_expires_at'), 'curated_resources', ['cache_expires_at'], unique=False)
    op.create_index(op.f('ix_curated_resources_learning_style'), 'curated_resources', ['learning_style'], unique=False)
    op.create_index(op.f('ix_curated_resources_topic'), 'curated_resources', ['topic'], unique=False)
    op.drop_index(op.f('idx_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_constraint(op.f('notification_preferences_user_id_key'), 'notification_preferences', type_='unique')
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.drop_index(op.f('idx_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_type'), table_name='notifications')
    op.drop_index(op.f('idx_notifications_user_id'), table_name='notifications')
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_index(op.f('idx_scheduled_reminders_is_active'), table_name='scheduled_reminders')
    op.drop_index(op.f('idx_scheduled_reminders_scheduled_time'), table_name='scheduled_reminders')
    op.drop_index(op.f('idx_scheduled_reminders_user_id'), table_name='scheduled_reminders')
    op.create_index(op.f('ix_scheduled_reminders_scheduled_time'), 'scheduled_reminders', ['scheduled_time'], unique=False)
    op.create_index(op.f('ix_scheduled_reminders_user_id'), 'scheduled_reminders', ['user_id'], unique=False)
    op.alter_column('semesters', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('semesters', 'start_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('semesters', 'end_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('semesters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_semesters_user_active'), table_name='semesters')
    op.alter_column('tasks', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks', 'user_course_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tasks', 'category',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('tasks', 'due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_tasks_completion'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_due_date'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_priority'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_course'), table_name='tasks')
    op.alter_column('user_courses', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_courses', 'course_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_courses', 'enrolled_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_courses', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_user_courses_predictions'), table_name='user_courses')
    op.drop_index(op.f('idx_user_courses_user_semester'), table_name='user_courses')
    op.drop_constraint(op.f('user_courses_user_id_semester_id_course_id_key'), 'user_courses', type_='unique')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_university_id'), table_name='users')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_index(op.f('idx_video_notes_created_at'), table_name='video_notes')
    op.drop_index(op.f('idx_video_notes_resource_id'), table_name='video_notes')
    op.drop_index(op.f('idx_video_notes_user_id'), table_name='video_notes')
    op.create_index(op.f('ix_video_notes_resource_id'), 'video_notes', ['resource_id'], unique=False)
    op.create_index(op.f('ix_video_notes_user_id'), 'video_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_notes_user_id'), table_name='video_notes')
    op.drop_index(op.f('ix_video_notes_resource_id'), table_name='video_notes')
    op.create_index(op.f('idx_video_notes_user_id'), 'video_notes', ['user_id'], unique=False)
    op.create_index(op.f('idx_video_notes_resource_id'), 'video_notes', ['resource_id'], unique=False)
    op.create_index(op.f('idx_video_notes_created_at'), 'video_notes', ['created_at'], unique=False)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_university_id'), 'users', ['university_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('user_courses_user_id_semester_id_course_id_key'), 'user_courses', ['user_id', 'semester_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_courses_user_semester'), 'user_courses', ['user_id', 'semester_id'], unique=False)
    op.create_index(op.f('idx_user_courses_predictions'), 'user_courses', ['predicted_grade_point'], unique=False)
    op.alter_column('user_courses', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_courses', 'enrolled_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_courses', 'course_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('user_courses', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_tasks_user_course'), 'tasks', ['user_course_id'], unique=False)
    op.create_index(op.f('idx_tasks_priority'), 'tasks', [sa.literal_column('priority_score DESC')], unique=False)
    op.create_index(op.f('idx_tasks_due_date'), 'tasks', ['due_date'], unique=False)
    op.create_index(op.f('idx_tasks_completion'), 'tasks', ['is_completed'], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('tasks', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('tasks', 'category',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('tasks', 'user_course_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('tasks', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_semesters_user_active'), 'semesters', ['user_id', 'is_active'], unique=False)
    op.alter_column('semesters', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('semesters', 'end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('semesters', 'start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('semesters', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_scheduled_reminders_user_id'), table_name='scheduled_reminders')
    op.drop_index(op.f('ix_scheduled_reminders_scheduled_time'), table_name='scheduled_reminders')
    op.create_index(op.f('idx_scheduled_reminders_user_id'), 'scheduled_reminders', ['user_id'], unique=False)
    op.create_index(op.f('idx_scheduled_reminders_scheduled_time'), 'scheduled_reminders', ['scheduled_time'], unique=False)
    op.create_index(op.f('idx_scheduled_reminders_is_active'), 'scheduled_reminders', ['is_active'], unique=False)
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.create_index(op.f('idx_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('idx_notifications_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('idx_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('idx_notifications_created_at'), 'notifications', [sa.literal_column('created_at DESC')], unique=False)
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.create_unique_constraint(op.f('notification_preferences_user_id_key'), 'notification_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.drop_index(op.f('ix_curated_resources_topic'), table_name='curated_resources')
    op.drop_index(op.f('ix_curated_resources_learning_style'), table_name='curated_resources')
    op.drop_index(op.f('ix_curated_resources_cache_expires_at'), table_name='curated_resources')
    op.drop_index('idx_topic_quality', table_name='curated_resources')
    op.drop_index('idx_topic_learning_style', table_name='curated_resources')
    op.drop_index('idx_resource_type_quality', table_name='curated_resources')
    op.create_index(op.f('idx_curated_topic_quality'), 'curated_resources', ['topic', 'quality_score'], unique=False)
    op.create_index(op.f('idx_curated_topic_learning_style'), 'curated_resources', ['topic', 'learning_style'], unique=False)
    op.create_index(op.f('idx_curated_topic'), 'curated_resources', ['topic'], unique=False)
    op.create_index(op.f('idx_curated_resource_type_quality'), 'curated_resources', ['resource_type', 'quality_score'], unique=False)
    op.create_index(op.f('idx_curated_learning_style'), 'curated_resources', ['learning_style'], unique=False)
    op.create_index(op.f('idx_curated_cache_expires'), 'curated_resources', ['cache_expires_at'], unique=False)
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.create_index(op.f('idx_courses_level'), 'courses', ['level'], unique=False)
    op.create_index(op.f('idx_courses_department'), 'courses', ['department'], unique=False)
    op.create_index(op.f('idx_courses_code'), 'courses', ['code'], unique=False)
    op.create_unique_constraint(op.f('courses_code_key'), 'courses', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('courses', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_content_curation_queries_topic'), table_name='content_curation_queries')
    op.drop_index(op.f('ix_content_curation_queries_created_at'), table_name='content_curation_queries')
    op.create_index(op.f('idx_curation_query_topic'), 'content_curation_queries', ['topic'], unique=False)
    op.create_index(op.f('idx_curation_query_created'), 'content_curation_queries', ['created_at'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('recommendation_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('recommendation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('priority_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_dismissed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('acted_on_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('recommendations_task_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('recommendations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('recommendations_pkey'))
    )
    op.create_index(op.f('idx_recommendations_user_active'), 'recommendations', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_recommendations_priority'), 'recommendations', ['priority_rank'], unique=False)
    op.create_table('moods',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('mood_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mood_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('energy_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('associated_task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('associated_course_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('logged_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['associated_course_id'], ['user_courses.id'], name=op.f('moods_associated_course_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['associated_task_id'], ['tasks.id'], name=op.f('moods_associated_task_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('moods_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('moods_pkey'))
    )
    op.create_index(op.f('idx_moods_user_date'), 'moods', ['user_id', sa.literal_column('logged_at DESC')], unique=False)
    op.create_index(op.f('idx_moods_sentiment'), 'moods', ['sentiment_score'], unique=False)
    op.create_table('gpa_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('semester_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('semester_gpa', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('cumulative_gpa', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('predicted_cgpa', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('credits_this_semester', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('classification', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('target_cgpa', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('gap_to_target', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('gpa_records_semester_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('gpa_records_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('gpa_records_pkey'))
    )
    op.create_index(op.f('idx_gpa_records_user_date'), 'gpa_records', ['user_id', sa.literal_column('recorded_at DESC')], unique=False)
    # ### end Alembic commands ###
